# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
    python: python3.10
repos:
-   repo: local
    hooks:
    - id: isort
      additional_dependencies:
        - isort
      name: isort
      entry: isort
      language: python
      types: [ python ]
      args: [--settings-path=setup.cfg]
    - id: black
      additional_dependencies:
        - black
      name: black
      entry: black
      language: python
      types: [python]
      args: ["--skip-string-normalization"]
    - id: flake8
      name: flake8
      entry: flake8
      language: python
      types: [ python ]
      additional_dependencies: [wemake-python-styleguide]
      args: [ --config=setup.cfg]
    - id: mypy
      additional_dependencies:
        - django
        - python-dotenv
        - django-utils-six
        - channels
        - channels-redis
        - daphne==4.0.0
        - mypy==1.8
        - django-stubs
        - psycopg2-binary
        - asyncpg
        - pydantic
      name: mypy
      entry: mypy
      language: python
      types: [python]
      args: [--config-file=setup.cfg]
    - id: lint-staged
      name: lint-staged
      additional_dependencies:
        - lint-staged@15.0.0
        - eslint@9.0.0-alpha.2
        - eslint-config-standard@latest
        - eslint-plugin-import@^2.25.2
        - eslint-plugin-n@^15.0.0
        - prettier@4.0.0-alpha.8
        - eslint-plugin-prettier
        - eslint-config-prettier
      description: ''
      entry: lint-staged --allow-empty --concurrent false
      language: node
      types_or: [ javascript, jsx, ts, tsx, css ]
      args: [ --config=front_config/lint-staged.config.js ]
      require_serial: false
      minimum_pre_commit_version: '0'
- repo: https://github.com/djlint/djLint
  rev: v1.34.1
  hooks:
    - id: djlint-reformat-django
      files: "\\.html"
      types_or: [ 'html' ]
      args: [ --configuration front_config/.djlintrc ]
    - id: djlint-django
      files: "\\.html"
      types_or: [ 'html' ]
      args: [ --configuration front_config/.djlintrc ]
