version: '3.7'

services:
  postgres:
    image: 'postgres:16-alpine3.19'
    container_name: 'postgres'
    env_file:
      - .env
    volumes:
      - database_data:/var/lib/postgresql/data/
    ports:
      - '8778:5432'
    #    expose:
    #      - 5432
    # uncommnet 'expose' and comment 'port' in production
  redis:
    image: redis:5
    container_name: 'redis'
    volumes:
      - redis_data:/data
    ports:
      - '6379:6379'
    #    expose:
    #      - 6379
    # uncommnet 'expose' and comment 'port' in production
  web:
    build:
      context: .
    command: daphne -b 0.0.0.0 -p 8000 deploy_config.asgi:application
    container_name: 'web'
    restart: always
    volumes:
      - ./:/usr/src/app
    expose:
      - 8000
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
  nginx:
    build:
      context: ./nginx/
    container_name: 'nginx'
    restart: always
    ports:
      - '80:80'
      - '443:443'
    expose:
      - 80
      - 443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d/
      - ./static:/usr/src/app/static
      - ./media:/usr/src/app/media
    depends_on:
      - web

volumes:
  database_data:
  redis_data: