vesion: '3.7'

services:
  postgres:
    image: 'postgres:16-alpine3.19'
    container_name: 'postgres'
    env_file:
      - .env
    volumes:
      - database_data:/var/lib/postgresql/data/
    ports:
      - '8778:5432'
#    expose:
#      - 5432
# uncommnet 'expose' and comment 'port' in production
  redis:
    image: redis:5
    container_name: 'redis'
    volumes:
      - redis_data:/data
    ports:
      - '6379:6379'
#    expose:
#      - 6379
# uncommnet 'expose' and comment 'port' in production
  web:
    build:
      context: .
    command: gunicorn config.wsgi:application --workers 3 --bind 0.0.0.0:8000
    container_name: 'web'
    restart: always
    volumes:
      - ./:/usr/src/app
    expose:
      - 8000
    env_file:
      - .env
    depends_on:
      - postgres
  daphne:
    build:
      context: .
      dockerfile: Dockerfile.daphne
    command: daphne -b 0.0.0.0 -p 8001 config.asgi:application
    container_name: 'daphne'
    restart: always
    volumes:
      - ./:/usr/src/app
    expose:
      - 8001
    env_file:
      - .env
    depends_on:
      - postgres
      - web
  nginx:
    build:
      context: ./nginx/
    container_name: 'nginx'
    restart: always
    ports:
      - '80:80'
      - '443:443'
    expose:
      - 80
      - 443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d/
      - ./static:/usr/src/app/static
      - gunicorn_socket:/gunicorn_socket
      - daphne_socket:/daphne_socket
    depends_on:
      - web
      - daphne

volumes:
  database_data:
  redis_data: